# Generated by Django 4.1.1 on 2022-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='img',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
    ]
