# Generated by Django 4.1.1 on 2022-10-03 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_work_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
