# Generated by Django 4.1.1 on 2022-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='city',
            field=models.CharField(default='Null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='country',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
